test: dev
hibernate:
    hibernate:
        cache:
            use_second_level_cache: false
    jdbc:
        batch_size: 20
    order_inserts: true
    order_updates: true
public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL42IpEXed0rV3AuMEInmpoyrcDmQRZ2Hy8ZTXLrnROTnv5HCRYRwA6LMTGps2kJyoqBbfLpAA0F/OP6e+qOLX0CAwEAAQ==
pwdroot: MzuKHFRrLywMwrn+KmhpkOXzIIU4hKEf8pvh4Di8Ff7UMWW11/nVksBzmFjPLSVjzCcnOBNZmrRrWMZA4+pGMA==
redis:
    host: 116.62.143.98
    password: maduar
    poolMaxIdle: 3
    poolMaxTotal: 10
    poolMaxWait: 3
    port: 6379
    timeout: 3
spring:
    datasource:
        connectionProperties: config.decrypt=true;config.decrypt.key=${public-key}
#        driver-class-name: net.sf.log4jdbc.DriverSpy
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,config
        initialSize: 1
        maxActive: 2
        maxOpenPreparedStatements: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 30000
        minIdle: 1
        password: ${pwdroot}
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://150.109.49.131:3306/sonar?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
#        url: jdbc:log4jdbc:mysql://150.109.49.131:3306/test?useUnicode=true&characterEncoding=utf8
        username: root
        validationQuery: SELECT 'x'
    thymeleaf:
        cache: false
        content-type: text/html
        enable: true
        encoding: UTF-8
        model: HTML5
        prefix: classpath:/templates/
        suffix: .html
