#激活哪一个环境的配置文件
#公共配置
spring:
  boot:
    admin:
      url: http://localhost:9000/
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: mmm
  mail:
    host: smtp.163.com
    username: maduar@163.com
    password: 163maduar310
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  rabbitmq:
    host: 150.109.49.131
    port: 5672
    username: guest
    password: rabbitMaduar310
  zipkin:
    sleuth:
      enable: false
      sampler:
        percentage: 1.0
logback_path: /Users/maduar/demo/log/${spring.application.name}

nacos.config.server-addr: 127.0.0.1:8848
useLocalCache: false
##management.security.enabled: false

#server:
#  context-path: /${spring.application.name}/api

appKey: 1
appSecret: 1
bucket: lynn
endPoint: https://www.aliyun.com

info:
  build:
#    artifact: @project.artifactId@
#    name: @project.name@
#    description: @project.description@
#    version: @project.version@

---
spring:
  profiles: dev
server:
  port: 8081
---
spring:
  profiles: test
server:
  port: 8082
---
spring:
  profiles: prd
server:
  port: 8083
