#激活哪一个环境的配置文件
#公共配置
spring:
  boot:
    admin:
      url: http://localhost:9000/
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: springbootdemo
  mail:
    host: smtp.163.com
    username: maduar@163.com
    password: 163maduar310
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#spring.boot.admin.url: http://mgmt:mgmtebiz@localhost:9000
##management.security.enabled: false

server:
  context-path: /${spring.application.name}/api

appKey: 1
appSecret: 1
bucket: lynn
endPoint: https://www.aliyun.com

info:
  build:
#    artifact: @project.artifactId@
#    name: @project.name@
#    description: @project.description@
#    version: @project.version@

---
spring:
  profiles: dev
server:
  port: 8081
---
spring:
  profiles: test
server:
  port: 8082
---
spring:
  profiles: prd
server:
  port: 8083
